use super::{hex, terminal, write_owned};
use crate::theme::Theme;

pub fn render(theme: &Theme) -> String {
    let colors = terminal::colors(theme);
    let mut text = String::from("-- Generated by Kajitsu; do not edit.\nreturn {\n");
    for (key, color) in [
        ("background", colors.background),
        ("foreground", colors.foreground),
        ("cursor_bg", colors.cursor),
        ("cursor_fg", theme.on_accent),
        ("cursor_border", colors.cursor),
        ("selection_bg", colors.selection),
        ("selection_fg", colors.foreground),
    ] {
        text.push_str(&format!("  {key} = '{}',\n", hex(color)));
    }
    for (name, values) in [("ansi", &colors.ansi[..8]), ("brights", &colors.ansi[8..])] {
        text.push_str(&format!("  {name} = {{"));
        for color in values {
            text.push_str(&format!(" '{}',", hex(*color)));
        }
        text.push_str(" },\n");
    }
    text.push_str("}\n");
    text
}

pub fn export(theme: &Theme) -> Result<(), String> {
    write_owned(
        &crate::paths::state_dir().join("wezterm-colors.lua"),
        &render(theme),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::integrations::{terminal, test_theme};

    #[test]
    fn serializes_light_and_dark_colors_with_two_eight_color_arrays() {
        for light in [false, true] {
            let theme = test_theme(light);
            let text = render(&theme);
            assert!(text.contains("background = '#010203'"));
            assert!(text.contains("foreground = '#f1f2f3'"));
            assert!(text.contains("cursor_bg = '#89b4fa'"));
            assert!(text.contains("cursor_fg = '#111111'"));
            assert!(text.contains("cursor_border = '#89b4fa'"));
            assert!(text.contains("selection_bg = '#223344'"));
            assert!(text.contains("selection_fg = '#f1f2f3'"));
            let colors = terminal::colors(&theme);
            for (name, expected) in [("ansi", &colors.ansi[..8]), ("brights", &colors.ansi[8..])] {
                let array = text
                    .split(&format!("{name} = {{"))
                    .nth(1)
                    .unwrap()
                    .split('}')
                    .next()
                    .unwrap();
                let values: Vec<_> = array.split(',').filter(|v| !v.trim().is_empty()).collect();
                assert_eq!(values.len(), 8);
                for (actual, expected) in values.iter().zip(expected) {
                    assert_eq!(
                        actual.trim().trim_matches('\''),
                        crate::integrations::hex(*expected)
                    );
                }
            }
        }
    }
}
